name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint all packages
        run: npm run lint --workspaces

      - name: Build backend
        run: npm --workspace backend run build

      - name: Build frontend
        run: npm --workspace frontend run build

      - name: Test backend
        run: npm --workspace backend run test
